### ISSUE TITLE
Extrinsic Failed

### ISSUE THREAD

**Issue by JeremyConnor** [jacogr/ink-sample-dns#1]
I followed the steps as mentioned in the readme file, and also added the @polkadot/util-crypto to package.json.
After running ```npm start``` I get the following error. I guess the error is due to insufficient gas.(I may be wrong regarding this statement)
![Screenshot from 2020-12-06 00-37-58](https://user-images.githubusercontent.com/73089748/101261191-5d315d80-375b-11eb-9876-4e24d2bc58f0.png)
![Screenshot from 2020-12-06 00-35-21](https://user-images.githubusercontent.com/73089748/101261192-5efb2100-375b-11eb-8b2f-b8697257a064.png)

**Comment by JeremyConnor** [comment]
Yes, the issue was with gas. I just increased it, and it worked.

**Comment by jacogr** [comment]
2 things here -

1. with the eviction it probably would make sense to increase the value (endowment) passed on creation as well. I actually tested this against canvas-node (my Substrate master was compiling), so the enconomics is probably slightly different on canvas as well. 

2. it was a quick coding over 20-odd minutes. When I have a gap to play will have to properly expand the error handling here (it is shocking) and add actual proper error decoding as well. (Module xxx, error yyy is not friendly)

**Comment by JeremyConnor** [comment]
@jacogr Will it be right to say that, you mapped the events to the transaction which helped you get the events? So, this mapping is being done by Polkadot UI but not by substrate node. Hence, what I was trying to do was getting successful but I could not map the events?

Is there any documentation of errors which I can look at, to debug errors that I encounter? The errors just display the Module number and the error number (for eg. ```Error. {"Module":{"index":9,"error":6}}```), which makes it difficult to know the cause of error.

**Comment by jacogr** [comment]
Added full decoding (as said in 2 above) in this commit - https://github.com/jacogr/ink-sample-dns/commit/c942dc1ecae7f1a31c6890293733952a4758a3dd

So if shows all the system events now as well and decodes all the errors (links to the relevant doc sections also included in the code)

Anyway, this cleans it up a bit better with a generic handler so less duplication of stuff.

**Comment by JeremyConnor** [comment]
@jacogr Is there any other way to import WASM and ABI instead of fs.readFileSync(), because readFileSync is not available for react native?
I also tried using Buffer, but it leads to ```Error: Invalid JSON ABI structure supplied, expected a recent metadata version```. 
Also, I don't think that there is anything wrong with the ABI, as I was able to deploy it using NodeJS script.

**Comment by jacogr** [comment]
Buffer should be fine - just toString() it. Alternatively require it? 

It can be a string (which will be parsed into an object) or the actual ABI object.

**Comment by jacogr** [comment]
Ie. Any of these should work - https://stackoverflow.com/questions/29452822/how-to-fetch-data-from-local-json-file-on-react-native

**Comment by JeremyConnor** [comment]
I used the code as here:
```
  const wasmHex = Buffer.from('AssetTransfer.wasm').toString('hex');
  const abiJson = Buffer.from('AssetTransfer.json', 'utf-8');
```

**Comment by jacogr** [comment]
Buffer.from() as used above creates a buffer containing the filename string. It doesn’t read it. You need a way to load the content.

**Comment by JeremyConnor** [comment]
Okay, that makes sense. But why won't readFile() work? As, readFile should return the content of the file.
I was also looking at https://stackoverflow.com/questions/60673807/how-to-load-wasm-file-in-react-native . Will this work?

**Comment by jacogr** [comment]
That should work yes. For the WASM, all it needs is the Uint8Array with the bytes, for the ABI it needs a string (or JSON-decoded). 

The example there, with fetch, it however quite broken :) So with fetch you get an object back, not the actual contents, see https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

So to get -

- the JSON from it (e.g. ABI), it is `await reponse.json()` (aka https://developer.mozilla.org/en-US/docs/Web/API/Body/json)
- for the WASM bytes, it woud be `await response.arrayBuffer()` (aka https://developer.mozilla.org/en-US/docs/Web/API/Body/arrayBuffer) and then just `Uint8Array.from(arrayBuffer)` (I believe)

**Comment by JeremyConnor** [comment]
Sorry to bother you @jacogr but, I am still getting ```Error: Invalid JSON ABI structure supplied, expected a recent metadata version```. Following is the piece of code I am using:
```
async function fetchJson(){
  const response = await fetch('AssetTransfer.json');
  const abi = await response.json();
  return abi;
}

async function fetchWasm(){
  const response = await fetch('AssetTransfer.wasm');
  const wasm = await response.arrayBuffer();
  return wasm;
}

// deploys a code bundle on-chain, returning a blueprint
async function getBlueprint (alice, api) {
  console.log('');

  const wasmHex = fetchWasm();
  const abiJson = fetchJson();

  // the code we are going to be working with
  const code = new CodePromise(api, abiJson, `0x${wasmHex}`);
  const tx = code.createBlueprint();

  return resultPromise('getBlueprint', tx, alice, ({ blueprint }) => blueprint);
}
```
This error occurs in case of React Native only, whereas, it works perfectly fine in case of NodeJS

**Comment by jacogr** [comment]
Weird, this look 100% above-board -

```
const response = await fetch('AssetTransfer.json');
const abi = await response.json();
```

What happens when you log the `abi` after retrieval? 

You can also try `response.text()` (which should yield the string - either the object or the text can be passed through, ti will parse the string if found)

**Comment by JeremyConnor** [comment]
So, when I try ```console.log(abi)```, it doesn't output anything.
I am getting 3 errors. 2 of them are 
```
Possible Unhandled Promise Rejection (id: 1): 
TypeError: Network request failed
```
and the 3rd error is 
```Error: Invalid JSON ABI structure supplied, expected a recent metadata version```
Here is the screenshot of the terminal screen
![Screenshot from 2020-12-07 21-33-00](https://user-images.githubusercontent.com/73089748/101374432-2b8fd200-38d4-11eb-8a5f-788bb1f0593c.png)

**Comment by jacogr** [comment]
So the issue is `Network request failed` - it couldn't retrieve anything.

**Comment by JeremyConnor** [comment]
But, what I don't understand is, why does fetch give ```Network request failed``` error when the data is present locally and I don't need to access any JSON via some URL? Any solution for this error?

**Comment by jacogr** [comment]
No idea about RN, sadly don't play much with it at all, there is only so many hours in a day. There are a number of approaches, as always, e.g. a simple Google search for reading files from RN brings up -

- https://www.npmjs.com/package/react-native-fs (and https://dev-yakuza.posstree.com/en/react-native/react-native-fs/)
- https://docs.expo.io/versions/latest/sdk/filesystem/
- https://awesomeopensource.com/project/wkh237/react-native-fetch-blob

etc.
